---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-csi-access
  labels:
    env: dev
    app.kubernetes.io/name: secrets-csi-access
    app.kubernetes.io/part-of: dev
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-csi-role
  labels:
    env: dev
    app.kubernetes.io/name: secrets-csi-role
    app.kubernetes.io/part-of: dev
subjects:
  - kind: ServiceAccount
    name: secrets-csi-gke
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: secrets-csi-access
  apiGroup: rbac.authorization.k8s.io/v1
